/*
|--------------------------------------------------------------------------
| Financial Dashboard
|--------------------------------------------------------------------------
*/
export const GET_FINANCIAL_DASHBOARD_REQUEST='GET_FINANCIAL_DASHBOARD_REQUEST';
export const GET_FINANCIAL_DASHBOARD_SUCCESS='GET_FINANCIAL_DASHBOARD_SUCCESS';
export const GET_FINANCIAL_DASHBOARD_FAIL='GET_FINANCIAL_DASHBOARD_FAIL';

export const GET_EXPENSE_BREAKDOWN_REQUEST='GET_EXPENSE_BREAKDOWN_REQUEST';
export const GET_EXPENSE_BREAKDOWN_SUCCESS='GET_EXPENSE_BREAKDOWN_SUCCESS';
export const GET_EXPENSE_BREAKDOWN_FAIL='GET_EXPENSE_BREAKDOWN_FAIL';

export const GET_PROJECT_PROFITABILITY_REQUEST='GET_PROJECT_PROFITABILITY_REQUEST';
export const GET_PROJECT_PROFITABILITY_SUCCESS='GET_PROJECT_PROFITABILITY_SUCCESS';
export const GET_PROJECT_PROFITABILITY_FAIL='GET_PROJECT_PROFITABILITY_FAIL';

export const GET_CASHFLOW_REQUEST='GET_CASHFLOW_REQUEST';
export const GET_CASHFLOW_SUCCESS='GET_CASHFLOW_SUCCESS';
export const GET_CASHFLOW_FAIL='GET_CASHFLOW_FAIL';