export const GET_PRICE_ALERTS_REQUEST =
    'GET_PRICE_ALERTS_REQUEST';
export const GET_PRICE_ALERTS_SUCCESS =
    'GET_PRICE_ALERTS_SUCCESS';
export const GET_PRICE_ALERTS_FAIL =
    'GET_PRICE_ALERTS_FAIL';

export const CREATE_PRICE_ALERT_REQUEST =
    'CREATE_PRICE_ALERT_REQUEST';
export const CREATE_PRICE_ALERT_SUCCESS =
    'CREATE_PRICE_ALERT_SUCCESS';
export const CREATE_PRICE_ALERT_FAIL =
    'CREATE_PRICE_ALERT_FAIL';

export const DELETE_PRICE_ALERT_REQUEST =
    'DELETE_PRICE_ALERT_REQUEST';
export const DELETE_PRICE_ALERT_SUCCESS =
    'DELETE_PRICE_ALERT_SUCCESS';
export const DELETE_PRICE_ALERT_FAIL =
    'DELETE_PRICE_ALERT_FAIL';