export const DELETE_PRICE_INDEX_REQUEST =
    'DELETE_PRICE_INDEX_REQUEST';

export const DELETE_PRICE_INDEX_SUCCESS =
    'DELETE_PRICE_INDEX_SUCCESS';

export const DELETE_PRICE_INDEX_FAIL =
    'DELETE_PRICE_INDEX_FAIL';