const mongoose=require('mongoose');

const NotificationSchema=new mongoose.Schema({
    recipient:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'User',
        required:true,
        index:true
    },
    sender:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'User',
        required:true
    },
    type:{
        type:String,
        enum:[
            'connection_request',
            'connection_accepted',
            'connection_rejected',
            'like',
            'comment',
            'follow',
            'marketplace',
            'price_alert',
            'farm',
            'system'
        ],
        required:true,
        index:true
    },
    title:{
        type:String,
        required:true,
        trim:true,
        maxlength:150
    },
    message:{
        type:String,
        required:true,
        trim:true,
        maxlength:500
    },
    link:{
        type:String,
        default:'',
        trim:true,
        maxlength:500
    },
    read:{
        type:Boolean,
        default:false,
        index:true
    }
},{
    timestamps:true
});

NotificationSchema.index({
    recipient:1,
    read:1,
    createdAt:-1
});

NotificationSchema.index({
    recipient:1,
    type:1,
    createdAt:-1
});

module.exports=mongoose.model('Notification',NotificationSchema);